authentication/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import home,signIn,signUp,resetPassword,\
    createPassword,dashboard


urlpatterns = [
    url('admin/', include(admin.site.urls)),

    url(r'^signIn/$',signIn,name="signIn"),
    url(r'^signUp/$',signUp,name="signUp"),
    url(r'^resetPassword/$',resetPassword,name="resetPassword"),
    url(r'^createPassword/$',createPassword,name="createPassword"),
    url(r'^dashboard/$',dashboard,name="dashboard"),
    url(r'^',home,name="home")
]

jd_builder/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns


urlpatterns = i18n_patterns(
    url('admin/', include(admin.site.urls)),
    url('social-auth/', include('social_django.urls', namespace='social')),
    url(r'^', include('authentication.urls', namespace="authentication"))

)

authentication/models.py
from django.db.models import CharField,IntegerField,DateField,Model,AutoField

# Create your models here.

class Clients(Model):
    ClientId=CharField(max_length=10)
    Email=CharField(max_length=100,primary_key=True)
    ClientName=CharField(max_length=150)
    Password=CharField(max_length=8)

    def __str__(self):
        return self.ClientId


class UserMasterTable(Model):
    UserId=CharField(max_length=10,primary_key=True)
    UserEmail=CharField(max_length=50)
    UserName=CharField(max_length=50)
    UserCompany=CharField(max_length=100)
    UserPassword=CharField(max_length=20)
    UserActiveStatus=IntegerField()
    UserCreatedBy=CharField(max_length=50)
    UserCreatedDate=DateField(max_length=8)
    UserUpdatedBy=CharField(max_length=50)
    UserUpdatedDate=DateField(max_length=8)

    def __str__(self):
        return self.UserId

authentication/forms.py
from django.forms import ModelForm
from .models import PasswordTable
from django import forms
from django.forms import Form


class SignUpForm(Form):
    Email=forms.CharField(widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'id':'password',
        'placeholder':'Enter Email Address'
        }
    ))

    Name=forms.CharField(widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'id':'password',
        'placeholder':'Enter Full Name'
        }
    ))
    Password=forms.CharField(widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'id': 'password',
        'placeholder':'Create Your  Password'
        }
    ))
    Retype_Password=forms.CharField(widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'id': 'password',
        'placeholder':'Create Your  Password'
        }
    ))

authentication/views.py
from django.shortcuts import render, redirect
import json
from .models import Clients
from django.http import HttpResponse


# Create your views here.

class DataX:
    def __init__(self,email):
        self.email=email
        self.currentUser=None

c_data=DataX(None)


def isEmail(email):
    client = Clients.objects.filter(Email=email)

    if client:
        return True,client

    return False,None


def home(request):
    if 'current_user' in request.session:
        return redirect('/dashboard/')
    return render(request,"index.html")

def signIn(request):

    try:

        if request.method=="POST":
            user=Clients.objects.filter(Email=request.POST.__getitem__('email'),Password=request.POST.__getitem__('password'))
            if user:
                 print("line number 38")
                 request.session['current_user']="kumar"#user
                 print("line number 40")
                 return render(request,"ProfilePage.html")

            from django.contrib import messages
            messages.warning(request,"Username or Password is incorrect!.")

        return render(request,"signIn.html")

    except Exception as e:
        return HttpResponse(e)

def signUp(request):

    def isSendConfirmationEmail(email):

        from django.core.mail import send_mail

        message_str = """
            Hello,
    
                We received a request to reset the password for your account for this email address. To initiate the password reset process for your account, click the link below.
    
                http://localhost:8000/createPassword/.
    
                This link can only be used once. If you need to reset your password again, please visit http://127.0.0.1:8000 and request another reset.
    
                If you did not make this request, you can simply ignore this email.
    
                Sincerely,
                The Website Team
    
            """

        if send_mail('From JD Builder', message_str, 'kumarisravel724298@gmail.com', [email], fail_silently=False, ):
            return True
        return False

    if request.method=="POST":
        import random

        try:
            is_Email,client=isEmail(request.POST.__getitem__('email'))

            if not is_Email:

                if True:#isSendConfirmationEmail(request.POST.__getitem__('email')):

                    client = Clients(ClientId=str(random.randint(1000,9999)),ClientName=request.POST.__getitem__('name'), Email=request.POST.__getitem__('email'), Password=request.POST.__getitem__('passwordConfirmed'))
                    client.save()

                    return render(request,"afterSignUp.html")

            from django.contrib import messages
            messages.warning(request,"Entered e-mail is already taken!.  Try with another e-mail!.")

        except Exception as e:

            json_data=json.dumps({'value':str(e)})

            return HttpResponse(json_data)

    return render(request,'signUp.html')

def resetPassword(request):

    if request.method=="POST":

        c_data.email = request.POST.__getitem__('email')

        is_Email,c_data.currentUser=isEmail(c_data.email)

        if is_Email:

            from django.core.mail import send_mail

            message_str="""
                Hello,
                    
                    We received a request to reset the password for your account for this email address. To initiate the password reset process for your account, click the link below.
                    
                    http://localhost:8000/createPassword/.
                    
                    This link can only be used once. If you need to reset your password again, please visit http://127.0.0.1:8000 and request another reset.
                    
                    If you did not make this request, you can simply ignore this email.
                    
                    Sincerely,
                    The Website Team
                
                """

            if True:#send_mail('From JD Builder',message_str,'kumarisravel724298@gmail.com',[c_data.email],fail_silently=False,):

                return render(request,"seeEmail.html",{'email':c_data.email})

        from django.contrib import messages

        messages.warning(request,"Entered e-mail is not registered one!.")

    return render(request,"forgetPassword.html")

def createPassword(request):

    if request.method=="POST":

        client=Clients.objects.filter(Email=c_data.email)

        client.update(Password=request.POST.__getitem__('passwordConfirmed'))

        return render(request,"successPasswordUpdation.html",{'user':c_data.currentUser[0].ClientName})

    return render(request,"passwordCreation.html")

def dashboard(request):

    return render(request,'ProfilePage.html')

templates/ProfilePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <h1>Welcome to JDBuilder</h1>
</body>
</html>

templates/afterSignUp.html
<!DOCTYPE HTML>

<html>

<head>
    <title>Untitled</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    {% load i18n %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script>
        $(document).ready(function(){
            alert("Applied Restriction over verifying the given email is applied on Development stage.");
        });

        function navigateToLogin(){
        window.location="{% url 'authentication:signIn' %}";
        }
        function navigateToEmail(){
        window.location="https://www.gmail.com/";
        }
    </script>
        <style>
        body,html
        {
                margin:0px;
                height:100%;
                position:relative;
                width:100%;
                background-color:#FFFFFF;
        }
        .body{
                margin: 0;
                position: absolute;
                top: 50%;
                -ms-transform: translateY(-50%);
                transform: translateY(-50%);
        }


        .t_scout_logo{
                display:block;
                margin-left:auto;
                margin-right:auto;
                width:60%;
                height:10%;
                padding:5%;
        }
        .container{
                line-height:1.5;
        }
                        /* increase the line height for container*/
        .container p{
                text-align:left;
                padding:5px;
                font-weight:bold;
                color:#7D7D7D;
                font-size:14px;
                font-family:"Gilroy-Bold";
        }
        .container .con-text{
            font-weight:normal;
            font-family:"Gilroy-Bold"s;
            font-size:12px;


        }



        input[type=submit],[type=button]{
                padding:10px;
                width:50%;
                border:none;
                background-color:#26B1FC;
                border-radius:3px;
                margin-left:auto;
                margin-right:auto;
                display:block;
                font-size:12px;
                color:#FFFFFF;
        }
        .other_texts{
                font-size:10px;
                color:#0052CC;
                text-decoration:none;
        }
        .t_souct_power{
                width:25%;
                margin-left:auto;
                margin-right:auto;
                display:inline;
                height:25px;
                float:right;
        }

        .footer{
        position:absolute;
        bottom:0px;
        width:100%;
        }




        @media screen and (min-width:480px){

                        .t_scout_logo{
                                width:50%;
                        }
                        .container p{
                                font-size:17px;
                        }

                        .container .con-text{
                                font-size:15px;
                        }

                        .other_texts{
                                font-size:11px;
                        }


                        input[type=submit],[type=button]{
                            width:40%;

                }

        }

        @media screen and (min-width:768px){
                        .t_scout_logo{
                                width:35%;
                                padding:0%;
                        }


                        .body{
                                width:95%;
                                left:2.5%;
                        }
                        .other_texts{
                                font-size:10px;
                        }

                        .t_souct_power{
                                width:15%;
                        }

                        input[type=submit],[type=button]{
                            width:25%;
                            margin-left:0px;
                        }


        }


        @media screen and (min-width:992px){
                        .t_scout_logo{
                                width:25%;
                                padding:0%;
                        }

                        .container p{
                                font-size:17px;
                        }
                        .container .con-text{
                                font-size:15px;
                        }


                        .other_texts{
                                font-size:12px;
                        }


                        .body{

                                width:95%;
                                left:2.5%;
                        }
                        .t_souct_power{
                                width:10%;
                        }
                        input[type=submit],[type=button]{
                            width:20%;


                        }
        }

    </style>

</head>

<body >
        <div class="body w3-container w3-center w3-animate-opacity">
                <form action="">

                        <div class="container">
                                        <img src="{% static 'assets\img\tscout_logo.png' %}" alt="" class="t_scout_logo" />

                                        <p >Sign Up Successful!</p>
                                        <p class="con-text">Hi Admin User, You have Successfully Signed Up! You are Now Being Sent a Confirmation E-Mail to Verify Your Email Address. Visit the Link Sent to you in this E-Mail will activate your account.
You have seven days to complete the account confirmation process. If you fail to do so within this period, the newly_registered Account may be purged.</p>


                                        <input type="button" value="Mail" onclick="navigateToEmail()" />

                                        <br>

                                        <input type="button" value="Login" onclick="navigateToLogin()"/>


                        </div>
                </form>
        </div>

        <span class="footer">
                &ensp;<a href="" class="other_texts">Privacy Poicy</a>
                &ensp;<a href="" class="other_texts">User Notice</a>
                <img src="{% static 'assets/img/tsout.png' %}" alt="" class="t_souct_power" />
        </span>

</body>


</html>

templates/passwordCreation.html
<!DOCTYPE HTML>

<html>

<head>
    <title>Untitled</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    {% load i18n %}
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

        <style>
        body,html
        {
                margin:0px;
                height:100%;
                position:relative;
                width:100%;
                background-color:#FFFFFF;
        }
        .body{
                margin: 0;
                position: absolute;
                top: 50%;
                -ms-transform: translateY(-50%);
                transform: translateY(-50%);
        }


        .t_scout_logo{
                display:block;
                margin-left:auto;
                margin-right:auto;
                width:60%;
                height:10%;
                padding:5%;
        }
        .container{

                line-height:1;
        }

        .container{
                padding:5px;
                font-weight:bold;
                color:#7D7D7D;
                font-family:"Gilroy-Bold";
        }

        .container .con-text{
                font-size:12px;
                text-align:left;
        }

        input[type=text],input[type=password]{
                width:100%;
                box-sizing:border-box;
                border:none;
                border-radius:2px;
                padding:12px 0px;
                border-bottom:2px solid #26B1FC;
                margin-right:auto;
                margin-left:auto;
                display:block;
                outline:none;
        }

        input[type=submit]{
                padding:10px;
                width:50%;
                border:none;
                background-color:#26B1FC;
                border-radius:3px;
                margin-left:auto;
                margin-right:auto;
                display:block;
                font-size:15px;
                color:#FFFFFF;
        }
        .other_texts{
                font-size:10px;
                color:#0052CC;
                text-decoration:none;
        }
        .privacy{
                width:100%;
                display:block;
                text-align:center;
                line-height:1.5;
        }
        .t_souct_power{
                width:25%;
                margin-left:auto;
                margin-right:auto;
                display:inline;
                height:25px;
                float:right;
        }

        .footer{
        position:absolute;
        bottom:0px;
        width:100%;
        }
        .nav_button{
            text-decoration:none;
            color:#26B1FC;
            font-size:12px;
        }

        input.ng-invalid.ng-dirty{
            border-bottom: 2px solid red;
        }
        input.ng-valid.ng-dirty{
            border-bottom: 3px solid #2AEB38;
        }

        .input_container{
            line-height:1;
        }

        @media screen and (min-width:480px){
                        .t_scout_logo{
                                width:60%;
                        }
                        .container p{
                                font-size:22px;
                        }
                        .container .con-text{
                                font-size:20px;
                        }
                        .other_texts{
                                font-size:11px;
                        }
                        .t_souct_power{
                                width:20%;
                        }

                    .nav_button{
                        font-size:15px;
                    }
                    input[type=submit]{
                        width:30%;
                    }


        }

        @media screen and (min-width:768px){
                        .t_scout_logo{
                                width:35%;
                                padding:0%;
                        }


                        .input_elements{
                                width:100%;
                                float:center;


                        }
                        input [type=text]{
                                width:100%;

                        }


                        .body{
                                width:70%;
                                left:15%;
                        }
                        .other_texts{
                                font-size:10px;
                        }
                        .t_souct_power{
                                width:15%;
                        }
                        .nav_button{
                            font-size:16px;
                        }
                        input[type=submit]{
                            width:20%;
                        }



        }


        @media screen and (min-width:992px){
                        .t_scout_logo{
                                width:32%;
                                padding:0%;
                        }

                        .container p{
                                font-size:20px;
                        }
                        .container .con-text{
                                font-size:18px;
                        }

                        .other_texts{
                                font-size:12px;
                        }

                        .input_elements{
                                width:100%;
                                float:center;


                        }
                        input [type=text]{
                                width:100%;

                        }

                        .body{

                                width:60%;
                                left:20%;
                        }
                        .t_souct_power{
                                width:10%;
                        }

                        .nav_button{
                            font-size:17px;
                        }
                        input[type=submit]{
                            width:15%;
                        }


        }

    </style>

</head>

<body >
        <script src="{% static 'javascript/jdBuilder.js' %}"></script>
        <script src="{% static 'javascript/jdController.js' %}"></script>

        <div class="body w3-container w3-center w3-animate-opacity">
                <form ng-app="jdBuilder" ng-controller="jdController" name="createPassword" novalidate action="{% url 'authentication:createPassword' %}" method="post">
                         {% csrf_token %}
                        <div class="container">
                                        <img src="{% static 'assets\img\tscout_logo.png' %}" alt="" class="t_scout_logo" />
                                        <p class="con-text">Create Password For Your Account</p>
                                        <div class="input_container">
                                        <div class="input_elements">
                                        <input type="password" name="firstPassword" ng-model="firstPassword" placeholder="Create Password" required/>
                                        </div>
                                        <br>
                                        <div class="input_elements">
                                        <input type="password" ng-model="passwordConfirmed" name="passwordConfirmed" placeholder="Confirm Password" compare-to="firstPassword" />

                                        <span style="color:red;float:left;" ng-show="createPassword.passwordConfirmed.$error.compareTo && createPassword.passwordConfirmed.$touched && createPassword.firstPassword.$touched">
                                            <span ng-show="createPassword.passwordConfirmed.$error">Password doesn't match</span>
                                        </span>

                                        </div>
                                        </div>

                                        <br>
                                        <br>

                                        <input type="submit" value="Submit" ng-disabled="createPassword.passwordConfirmed.$error.compareTo || createPassword.passwordConfirmed.$error.required || createPassword.firstPassword.$error.required" />
                                        <br>
                                        <a href="{% url 'authentication:signIn' %}" class="nav_button">Go back to Login</a>

                        </div>
                </form>
        </div>

        <span class="footer">
                &ensp;<a href="" class="other_texts">Privacy Poicy</a>
                &ensp;<a href="" class="other_texts">User Notice</a>
                <img src="{% static 'assets/img/tsout.png' %}" alt="" class="t_souct_power" />

        </span>

</body>


</html>

templates/seeEmail.html
<!DOCTYPE HTML>

<html>

<head>
    <title>Untitled</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    {% load i18n %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script>
        $(document).ready(function(){
            alert('Please visit http://localhost:8000/createPassword/ for resetting your password.');
        });


        function navigateToLogin(){
        window.location="{% url 'authentication:signIn' %}";
        }
        function navigateToEmail(){
        window.location="https://www.gmail.com/";
        }
    </script>
        <style>
        body,html
        {
                margin:0px;
                height:100%;
                position:relative;
                width:100%;
                background-color:#FFFFFF;
        }
        .body{
                margin: 0;
                position: absolute;
                top: 50%;
                -ms-transform: translateY(-50%);
                transform: translateY(-50%);
        }


        .t_scout_logo{
                display:block;
                margin-left:auto;
                margin-right:auto;
                width:60%;
                height:10%;
                padding:5%;
        }
        .container{
                line-height:1.5;
        }
                        /* increase the line height for container*/
        .container p{
                text-align:left;
                padding:5px;
                font-weight:bold;
                color:#7D7D7D;
                font-size:14px;
                font-family:"Gilroy-Bold";
        }
        .container .con-text{
            font-weight:normal;
            font-family:"Gilroy-Bold"s;
            font-size:12px;


        }



        input[type=submit],[type=button]{
                padding:10px;
                width:50%;
                border:none;
                background-color:#26B1FC;
                border-radius:3px;
                margin-left:auto;
                margin-right:auto;
                display:block;
                font-size:12px;
                color:#FFFFFF;
        }
        .other_texts{
                font-size:10px;
                color:#0052CC;
                text-decoration:none;
        }
        .t_souct_power{
                width:25%;
                margin-left:auto;
                margin-right:auto;
                display:inline;
                height:25px;
                float:right;
        }

        .footer{
        position:absolute;
        bottom:0px;
        width:100%;
        }




        @media screen and (min-width:480px){

                        .t_scout_logo{
                                width:50%;
                        }
                        .container p{
                                font-size:17px;
                        }

                        .container .con-text{
                                font-size:15px;
                        }

                        .other_texts{
                                font-size:11px;
                        }


                        input[type=submit],[type=button]{
                            width:40%;

                }

        }

        @media screen and (min-width:768px){
                        .t_scout_logo{
                                width:35%;
                                padding:0%;
                        }


                        .body{
                                width:95%;
                                left:2.5%;
                        }
                        .other_texts{
                                font-size:10px;
                        }

                        .t_souct_power{
                                width:15%;
                        }

                        input[type=submit],[type=button]{
                            width:25%;
                            margin-left:0px;
                        }


        }


        @media screen and (min-width:992px){
                        .t_scout_logo{
                                width:25%;
                                padding:0%;
                        }

                        .container p{
                                font-size:17px;
                        }
                        .container .con-text{
                                font-size:15px;
                        }


                        .other_texts{
                                font-size:12px;
                        }


                        .body{

                                width:95%;
                                left:2.5%;
                        }
                        .t_souct_power{
                                width:10%;
                        }
                        input[type=submit],[type=button]{
                            width:20%;


                        }
        }

    </style>

</head>

<body >
        <div class="body w3-container w3-center w3-animate-opacity">
                <form action="">

                        <div class="container">
                                        <img src="{% static 'assets\img\tscout_logo.png' %}" alt="" class="t_scout_logo" />

                                        <p >Please verify the entered E-mail!</p>
                                        <p class="con-text">Let's make you to dive into creating password by clicking the verification link which is sent in by us to {{ email }}.</p>
                                        <input type="button" value="Mail" onclick="navigateToEmail()" />



                        </div>
                </form>
        </div>

        <span class="footer">
                &ensp;<a href="" class="other_texts">Privacy Poicy</a>
                &ensp;<a href="" class="other_texts">User Notice</a>
                <img src="{% static 'assets/img/tsout.png' %}" alt="" class="t_souct_power" />
        </span>

</body>


</html>